### ISSUE TITLE
Registry Installation Error - cannot download archive in Mason

### ISSUE THREAD

**Issue by 50-Course** [nvim-java/mason-registry#26]
During a recent upgrade process to update my mason packages, Mason to download from nvim-java's mirror therefore,
breaking my download exp. as well as user exp. 

Every now and then a new buffer would spun up in attempt to download the required registry, however, due to failure,
wouldn't be able to complete the process.

### Error

```
Registry installation failed with the following error:
    GitHubRegistrySource(repo=nvim-java/mason-registry) failed to install: Failed to download registry archive.
```

### Environment config

Editor: Neovim
Build: Nightly (11-dev)
OS: Linux (Ubuntu)

**Comment by 50-Course** [comment]
thanks for the reply @s1n7ax - this happened in a `PackerSync` operation. Just found out i didn't mention `packer` as my plug manager back there

**Comment by s1n7ax** [comment]
Your config is on github?

**Comment by 50-Course** [comment]
yes, uhm... https://github.com/50-Course/nvim-config/blob/main/lua/codemage/mason.lua

**Comment by 50-Course** [comment]
Hi @s1n7ax making a quick check-in that the update now goes though and with that marking this as resolved. Thank you.
